export const LOAD_SINGLE_ALBUM_SUCCESS = "LOAD_SINGLE_ALBUM_SUCCESS";
export const LOAD_ALBUM_LIST_SUCCESS = "LOAD_ALBUM_LIST_SUCCESS";
export const LOAD_ALBUM_CONTENTS_SUCCESS = "LOAD_ALBUM_CONTENTS_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
